server {
    listen 80;
    server_name localhost;

    resolver 127.0.0.11 valid=30s;

    client_max_body_size 10m;

    location /uploads/ {
        alias /uploads/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location = /_internal/auth {
        internal;
        set $auth_backend http://user-service:8000/internal/verify;
        proxy_pass $auth_backend;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header Authorization $http_authorization;
    }

    location ~ ^/api/users/(register|verify-email|login|refresh|logout|forgot-password|reset-password) {
        set $user_svc http://user-service:8000;
        proxy_pass $user_svc;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ~ ^/api/wishlists/shared/ {
        set $wishlist_svc http://wishlist-service:8000;
        proxy_pass $wishlist_svc;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/users/ {
        auth_request /_internal/auth;
        auth_request_set $user_id $upstream_http_x_user_id;
        auth_request_set $is_admin $upstream_http_x_user_is_admin;
        proxy_set_header X-User-Id $user_id;
        proxy_set_header X-User-Is-Admin $is_admin;
        set $user_svc http://user-service:8000;
        proxy_pass $user_svc;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/wishlists/ {
        auth_request /_internal/auth;
        auth_request_set $user_id $upstream_http_x_user_id;
        auth_request_set $is_admin $upstream_http_x_user_is_admin;
        proxy_set_header X-User-Id $user_id;
        proxy_set_header X-User-Is-Admin $is_admin;
        set $wishlist_svc http://wishlist-service:8000;
        proxy_pass $wishlist_svc;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/reservations/ {
        auth_request /_internal/auth;
        auth_request_set $user_id $upstream_http_x_user_id;
        auth_request_set $is_admin $upstream_http_x_user_is_admin;
        proxy_set_header X-User-Id $user_id;
        proxy_set_header X-User-Is-Admin $is_admin;
        set $reserv_svc http://reservation-service:8000;
        proxy_pass $reserv_svc;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        set $frontend_svc http://frontend:80;
        proxy_pass $frontend_svc;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_intercept_errors on;
        error_page 404 = @frontend_fallback;
    }

    location @frontend_fallback {
        set $frontend_svc http://frontend:80;
        rewrite ^(.*)$ /index.html break;
        proxy_pass $frontend_svc;
    }
}
